services:
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=senhaForte
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=techcorp
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senhaForte
      POSTGRES_DB: techcorp
    ports:
      - '5432:5432'
